wandb_version: 1

debug:
  desc: null
  value: false
env:
  desc: null
  value: FrankaKitchen-v1
project:
  desc: null
  value: Kitchen_MultiTask
total_timesteps:
  desc: null
  value: 10000000
checkpoints:
  desc: null
  value: 10
tasks:
  desc: null
  value:
  - bottom burner
  - top burner
  - light switch
  - slide cabinet
  - microwave
  - kettle
policy:
  desc: null
  value: CostumAC
algorithm:
  desc: null
  value:
    name: SAC
    module: stable_baselines3
    args:
      learning_rate: 0.0003
      buffer_size: 1000000
      learning_starts: 100
      batch_size: 256
      tau: 0.005
      gamma: 0.99
      train_freq: 1
      gradient_steps: 1
      action_noise: null
      seed: null
      device: cuda:0
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.0b1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699442657.966823
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.11.2
      5: 0.16.0b1
      8:
      - 5
      13: linux-x86_64
