wandb_version: 1

debug:
  desc: null
  value: false
project:
  desc: null
  value: Kitchen_MultiTask
total_timesteps:
  desc: null
  value: 100000000
checkpoints:
  desc: null
  value: 10
env:
  desc: null
  value:
    name: FrankaKitchen-v1
    args:
      tasks_to_complete:
      - microwave
policy:
  desc: null
  value:
    name: MlpPolicy
    module: stable_baselines3.ppo.policies
algorithm:
  desc: null
  value:
    name: PPO
    module: stable_baselines3
    args:
      learning_rate: 0.0003
      n_steps: 2048
      batch_size: 64
      n_epochs: 10
      gamma: 0.99
      gae_lambda: 0.95
      clip_range: 0.2
      clip_range_vf: null
      normalize_advantage: true
      ent_coef: 0.0
      vf_coef: 0.5
      max_grad_norm: 0.5
      use_sde: false
      sde_sample_freq: -1
      target_kl: null
      stats_window_size: 100
      seed: null
      device: cuda:0
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.0b1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699451477.764849
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.11.2
      5: 0.16.0b1
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 10000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1699451479319776890
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: /home/joel/PhD/results/models/baseline/ch22p83h
_last_obs:
  desc: null
  value: "[[ 1.47832511e-01 -1.76923185e+00  1.84453671e+00 -2.47757469e+00\n   2.60979144e-01\
    \  7.11717549e-01  1.59596868e+00  4.72265603e-02\n   3.79660616e-02  8.52889626e-04\
    \  2.06201911e-04 -1.96320195e-05\n  -8.24428329e-04 -7.67485044e-05 -9.28498981e-04\
    \ -8.92853181e-04\n   2.32552074e-04 -6.12261845e-04 -2.45100693e-04 -5.30565259e-05\n\
    \   3.20407723e-05 -4.51537942e-05 -4.08387974e-06 -4.21367185e-05\n   6.27535639e-05\
    \  4.04783757e-05  4.62975876e-04 -2.26598355e-04\n  -4.67047986e-04 -6.44344834e-03\
    \ -1.75564990e-03  1.11481932e-03\n  -2.69438003e-01  3.50380852e-01  1.61944589e+00\
    \  9.99968535e-01\n   4.06618926e-03 -6.53311930e-03 -2.96192514e-04  1.50196121e-06\n\
    \  -5.69568886e-07 -6.18198901e-08 -1.89671201e-06  7.76781601e-07\n  -2.01884219e-07\
    \  5.45486642e-07  1.60764668e-06  1.01318594e-06\n   8.62702922e-07  1.38643141e-06\
    \  2.50586041e-06 -1.49648416e-05\n   9.48244495e-06  2.19795744e-06 -2.53762923e-07\
    \ -1.89709488e-06\n   4.66294751e-05 -3.17766885e-06 -4.55965868e-05  1.08009684e-03\n\
    \  -7.50000000e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (61,), float64)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (9,), float64)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f2646d6d080>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f25836a2520>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f258c500f10>
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f2580117750>
