version: '3'
services:
  gym:
    image: jbaptista99/gym:1.0
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    command: 
     - "bash" 
     - "-c"
     - ./code/multi_task_RL/docker/train.sh ${EXPERIMENT}
    runtime: nvidia
    ipc: host
    ulimits:
      memlock: -1
      stack: 12108864
    network_mode: host
    volumes:
      - $PHD_ROOT/multi_task:RL:/home/gymnasium/code
      - $PHD_RESULTS/logs:/home/gymnasium/logs
      - $PHD_RESULTS/models:/home/gymnasium/models
    deploy:
      replicas: ${TRAIN_REPLICAS}  # Set the desired number of replicas
