wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.0b1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699375619.6227
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 22
      - 23
      - 35
      4: 3.11.2
      5: 0.16.0b1
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'models.testings.PPO_exp.CostumAC'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1699375622778437600
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: /home/joel/PhD/results/models/baseline/28jw0o4j
_last_obs:
  desc: null
  value: "[[ 1.48872153e-01 -1.76759535e+00  1.84293982e+00 -2.47591136e+00\n   2.59378389e-01\
    \  7.11816317e-01  1.59591635e+00  4.73503318e-02\n   3.76892891e-02 -3.05524966e-04\
    \  3.85711990e-05  7.46113386e-04\n  -2.70825010e-04  3.60587390e-05  8.32492704e-05\
    \  3.63405299e-04\n   2.52692499e-04 -1.27501317e-04 -2.61003375e-04 -5.07052603e-05\n\
    \   2.90123541e-05 -4.48725903e-05 -4.05548007e-06 -4.22194539e-05\n   6.25934204e-05\
    \  4.04395408e-05  4.62792796e-04 -2.27738364e-04\n  -4.64417251e-04 -6.43893779e-03\
    \ -1.77850169e-03  1.10943787e-03\n  -2.69447311e-01  3.50385015e-01  1.61944871e+00\
    \  9.99969475e-01\n   4.04942821e-03 -6.56730637e-03 -2.67805509e-04  2.29535784e-06\n\
    \  -2.11867913e-06  2.11274863e-06  2.35432389e-06 -1.35049296e-07\n   2.09397450e-06\
    \ -3.00392353e-07  9.04875902e-07 -2.20306652e-06\n   2.23463508e-06 -4.40670905e-07\
    \ -3.72704849e-05 -4.56291890e-05\n  -1.08690590e-05 -2.34742583e-06 -1.95904384e-06\
    \  2.27153374e-06\n  -3.59967061e-05  7.52771631e-06 -4.15672490e-05  1.08009684e-03\n\
    \  -7.50000000e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f33f5290b50>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (61,), float64)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (9,), float64)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f33f46e8f40>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f33f46b77e0>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f33f5221110>
policy:
  desc: null
  value: "CostumAC(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n\
    \    (policy_net): Sequential(\n      (0): Linear(in_features=61, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n      (0):\
    \ Linear(in_features=61, out_features=64, bias=True)\n      (1): Tanh()\n    \
    \  (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=9, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f33f5b74f50>
