wandb_version: 1

debug:
  desc: null
  value: false
env:
  desc: null
  value: FrankaKitchen-v1
project:
  desc: null
  value: Kitchen_MultiTask
total_timesteps:
  desc: null
  value: 1000000
tasks:
  desc: null
  value:
  - bottom burner
  - top burner
  - light switch
  - slide cabinet
  - microwave
  - kettle
policy:
  desc: null
  value: CostumAC
algorithm:
  desc: null
  value:
    name: PPO
    args:
      learning_rate: 0.0003
      n_steps: 2048
      batch_size: 64
      n_epochs: 10
      gamma: 0.99
      gae_lambda: 0.95
      clip_range: 0.2
      clip_range_vf: null
      normalize_advantage: true
      ent_coef: 0.0
      vf_coef: 0.5
      max_grad_norm: 0.5
      use_sde: false
      sde_sample_freq: -1
      target_kl: null
      stats_window_size: 100
      seed: null
      device: cuda:0
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.0b1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699374978.777235
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.11.2
      5: 0.16.0b1
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'models.testings.PPO_exp.CostumAC'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1699374979578770829
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: None
_last_obs:
  desc: null
  value: "[[ 1.48291798e-01 -1.76785937e+00  1.84379789e+00 -2.47750212e+00\n   2.59843570e-01\
    \  7.11580093e-01  1.59581386e+00  4.82022281e-02\n   3.70822013e-02  9.43642362e-04\
    \ -7.70078400e-04 -3.56274114e-04\n   7.33582288e-04 -9.96526746e-04 -8.08294911e-04\
    \ -3.26753070e-04\n   3.76939184e-04 -9.78949758e-04 -2.70605801e-04 -5.08836725e-05\n\
    \   3.30964293e-05 -4.48830033e-05 -4.11492461e-06 -4.20463228e-05\n   6.28193492e-05\
    \  4.05672082e-05  4.62647957e-04 -2.26347408e-04\n  -4.64840366e-04 -6.44205290e-03\
    \ -1.81953544e-03  1.09312909e-03\n  -2.69406390e-01  3.50383894e-01  1.61944469e+00\
    \  9.99969746e-01\n   3.99169981e-03 -6.54667410e-03 -2.61519213e-04 -2.12065492e-06\n\
    \  -5.46187954e-07  2.47453337e-06  1.21035446e-06 -1.02605117e-06\n  -2.34395799e-06\
    \  1.20478802e-06  1.44388300e-06 -4.73260856e-07\n   2.37654853e-06  5.25307598e-07\
    \ -2.07055909e-05  1.94018319e-05\n   3.35042061e-05  9.76545348e-07 -2.20385502e-06\
    \ -2.21694781e-06\n   8.46775678e-06 -1.97911269e-05  2.07839499e-05  1.08009684e-03\n\
    \  -7.50000000e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (61,), float64)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (9,), float64)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f8c10a90ae0>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f8c10a4b380>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f8c110e1d10>
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f8c10d59390>
